"""DataCentric template strategy — auto-scaffolded.

Source: Data_Centric.pptx
Aspect: 16:9
Detected layouts: 11

⚠️  This file was auto-generated by scaffold_template_class.py.
    Review every TODO comment before using in production.
"""
from .base import TemplateStrategy
from ..models import SlideLayout


class DataCentricStrategy(TemplateStrategy):
    template_file = "Data_Centric.pptx"

    layout_map = {
        SlideLayout.TITLE      : 0,   # detected: "Titelfolie"
        SlideLayout.SECTION    : 2,   # detected: "Abschnitts- überschrift"
        SlideLayout.BULLETS    : 1,   # detected: "Titel und Inhalt"
        SlideLayout.TWO_COLUMN : 3,   # detected: "Zwei Inhalte"
        SlideLayout.IMAGE_LEFT : 5,   # detected: "Nur Titel"
        SlideLayout.IMAGE_RIGHT: 8,   # detected: "Bild mit Überschrift"
        SlideLayout.KEY_STATS  : 7,   # detected: "Inhalt mit Überschrift"
        SlideLayout.COMPARISON : 4,   # detected: "Vergleich"
        SlideLayout.CONCLUSION : 9,   # detected: "Titel und vertikaler Text"
    }

    placeholder_map = {
        "title"     : 0,
        "body"      : 1,
        "body_right": 2,
        # "body_col2": TODO  # not detected — verify or remove
        # "body_col3": TODO  # not detected — verify or remove
        # "picture": TODO  # not detected — verify or remove
        "slide_num" : 12,
    }

    font_scale = 1.0  # TODO: tune if rendered text looks too big/small
    aspect_ratio = (13.33, 7.5)


# ────────────────────────────────────────────────
# Detection report (for reference)
# ────────────────────────────────────────────────
# Layouts found:
#   [0] "Titelfolie" — idx=0(CENTER_TITLE), idx=1(SUBTITLE), idx=10(DATE), idx=11(FOOTER), idx=12(SLIDE_NUMBER)
#   [1] "Titel und Inhalt" — idx=0(TITLE), idx=1(OBJECT), idx=10(DATE), idx=11(FOOTER), idx=12(SLIDE_NUMBER)
#   [2] "Abschnitts- überschrift" — idx=0(TITLE), idx=1(BODY), idx=10(DATE), idx=11(FOOTER), idx=12(SLIDE_NUMBER)
#   [3] "Zwei Inhalte" — idx=0(TITLE), idx=1(OBJECT), idx=2(OBJECT), idx=10(DATE), idx=11(FOOTER)
#   [4] "Vergleich" — idx=0(TITLE), idx=1(BODY), idx=2(OBJECT), idx=4(OBJECT), idx=10(DATE)
#   [5] "Nur Titel" — idx=0(TITLE), idx=10(DATE), idx=11(FOOTER), idx=12(SLIDE_NUMBER)
#   [6] "Leer" — idx=10(DATE), idx=11(FOOTER), idx=12(SLIDE_NUMBER)
#   [7] "Inhalt mit Überschrift" — idx=0(TITLE), idx=1(OBJECT), idx=2(BODY), idx=10(DATE), idx=11(FOOTER)
#   [8] "Bild mit Überschrift" — idx=0(TITLE), idx=1(PICTURE), idx=2(BODY), idx=10(DATE), idx=11(FOOTER)
#   [9] "Titel und vertikaler Text" — idx=0(TITLE), idx=1(BODY), idx=10(DATE), idx=11(FOOTER), idx=12(SLIDE_NUMBER)
#   [10] "Vertikaler Titel und Text" — idx=0(TITLE), idx=1(BODY), idx=10(DATE), idx=11(FOOTER), idx=12(SLIDE_NUMBER)
